import test from 'node:test';import assert from 'node:assert/strict';
import {parseStatementCsv,parseStatementPdfLines,pdfPageLines,allocatedCashRows,suggestStatementCategory} from '../statements.mjs';
import {totals,categoryTotals} from '../finance.mjs';
const categories=[{id:'market',name:'MERCADO',type:'expense'},{id:'health',name:'SAÚDE',type:'expense'},{id:'extra',name:'EXTRAS',type:'expense'},{id:'reimburse',name:'REEMBOLSÁVEIS',type:'expense'}];
test('XP prior payment is excluded while refunds and merchant payments remain',()=>{
 const r=parseStatementCsv('Data;Estabelecimento;Portador;Valor;Parcela\n01/01/2026;Loja;Titular;R$ 100,00;-\n02/01/2026;  Pagamentos Válidos Normais;Titular;R$ -900,00;-\n03/01/2026;Estorno Loja;Titular;R$ -10,00;-\n04/01/2026;PG *LEROY MERLIN;Titular;R$ 20,00;-');
 assert.equal(r.excluded.length,1);assert.equal(r.total,110);assert.equal(r.items.length,3);assert.equal(r.items[1].amount,-10);assert.equal(r.invalid.length,0);
});
test('Nubank headers, payment exclusion, IOF and unknown merchants',()=>{
const r=parseStatementCsv('date,title,amount\n2026-09-01,Supermercado Chama,"64,86"\n2026-09-02,Drogasil,"21,99"\n2026-09-03,Desconhecido,"8,00"\n2026-09-04,Pagamento recebido,"- 891,06"',categories);
assert.equal(r.total,94.85);assert.equal(r.excluded.length,1);assert.deepEqual(r.items.map(x=>x.category_id),['market','health','extra']);
});
test('XP repeated installment lines are retained as separate stable occurrences',()=>{const csv='Data;Estabelecimento;Portador;Valor;Parcela\n06/09/2026;TURISMO;TITULAR;R$ 106,68;1 de 3\n06/09/2026;TURISMO;TITULAR;R$ 106,68;1 de 3';const a=parseStatementCsv(csv,categories),b=parseStatementCsv(csv,categories);assert.equal(a.items.length,2);assert.equal(a.total,213.36);assert.notEqual(a.items[0].key,a.items[1].key);assert.deepEqual(a.items.map(i=>i.key),b.items.map(i=>i.key));});
test('categorization learns exact merchant without inheriting reimbursable payments',()=>{assert.equal(suggestStatementCategory('Minha loja','',categories,[{description:'Minha loja',category_id:'health'}]).category_id,'health');assert.equal(suggestStatementCategory('Minha loja','',categories,[{description:'Minha loja',category_id:'reimburse'}]).category_id,'extra');});
test('PDF CAIXA offsets, credits and previous payment are parsed without unrelated column',()=>{
const items=[{str:'11/06',x:315,y:394},{str:'LOJA',x:331,y:395},{str:'02 DE 03',x:399,y:395},{str:'136,23D',x:550,y:394},{str:'JUROS 10%',x:20,y:394}];const lines=pdfPageLines(items);assert.equal(lines.length,1);assert.ok(!lines[0].includes('JUROS'));const r=parseStatementPdfLines([...lines,'13/07 AJUSTE CREDITO 0,01C','27/07 OBRIGADO PELO PAGAMENTO 4.622,10C','10/07 TOTAL DA FATURA ANTERIOR 4.622,10D'],2026,categories);assert.equal(r.items.length,2);assert.equal(r.total,136.22);assert.equal(r.excluded.length,2);assert.equal(r.items[0].parcel,'02 DE 03');});
test('cash allocation preserves cents, partial payments, credits and unmatched residual',()=>{
const cash={id:'payment',amount:30.01,type:'expense',date:'2026-09-20'};const items=[{id:'1',credit_card_id:'card',billing_cycle_id:'cycle',category_id:'market',type:'expense',amount:60},{id:'2',credit_card_id:'card',billing_cycle_id:'cycle',category_id:'health',type:'expense',amount:30},{id:'3',credit_card_id:'card',billing_cycle_id:'cycle',category_id:'market',type:'income',amount:10}];const rows=allocatedCashRows([cash,...items],[{transaction_id:'payment',billing_cycle_id:'cycle'}],[{id:'cycle',total_spent:100}]);assert.equal(totals(rows).expense,30.01);assert.deepEqual(rows.map(x=>x.amount),[15.01,9,6]);assert.equal(categoryTotals(items,categories).find(c=>c.id==='market').value,50);assert.equal(totals(items).expense,80);assert.equal(totals(items).income,0);
});
test('invalid rows are surfaced and overitemized statement does not inflate cash reports',()=>{const r=parseStatementCsv('date,title,amount\n31/02/2026,Invalid,10\n2026-09-01,Valid,20',categories);assert.equal(r.invalid.length,1);const cash={id:'payment',amount:50,type:'expense'};const items=[{credit_card_id:'card',billing_cycle_id:'cycle',amount:200,type:'expense'}];assert.deepEqual(allocatedCashRows([cash,...items],[{transaction_id:'payment',billing_cycle_id:'cycle'}],[{id:'cycle',total_spent:100}]),[cash]);});
