const {chromium}=require('playwright');const fs=require('node:fs'),path=require('node:path');
const email=process.env.CONTROLEGASTOS_LOGIN_EMAIL,password=process.env.CONTROLEGASTOS_LOGIN_PASSWORD;delete process.env.CONTROLEGASTOS_LOGIN_EMAIL;delete process.env.CONTROLEGASTOS_LOGIN_PASSWORD;
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1080},timezoneId:'America/Cuiaba'});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text().replace(/eyJ[^\s]+/g,'[redacted]'));});
try{await page.route('**/rest/v1/**',async route=>{if(new URL(route.request().url()).pathname==='/rest/v1/rpc/get_finance_workspace'&&route.request().method()==='POST'){await route.continue();return;}if(route.request().method()!=='GET'&&route.request().method()!=='HEAD'&&route.request().method()!=='OPTIONS'){await route.abort();throw Error('Unexpected write during read-only browser check');}await route.continue();});await page.goto(process.env.CONTROLEGASTOS_WEB_URL||'http://127.0.0.1:4173');await page.locator('#login-email').fill(email);await page.locator('#login-password').fill(password);await page.locator('#login-submit').click();await page.locator('#app').waitFor({state:'visible'});await page.locator('.kpi-value').first().waitFor({timeout:45000});fs.mkdirSync(path.join(__dirname,'../.local-tools/screenshots'),{recursive:true});await page.screenshot({path:path.join(__dirname,'../.local-tools/screenshots/overview-desktop.png'),fullPage:true});
const views=['transactions','cards','reports','dna','accounts','categories','investments','pending','import'];for(const view of views){await page.locator(`a[href="#${view}"]`).first().click();await page.waitForTimeout(150);if(await page.locator('#content h1').count()!==1)throw Error('Missing heading on '+view);}
await page.locator('a[href="#transactions"]').first().click();await page.locator('[data-action="filter-all"]').click();const countText=await page.locator('.totals-strip .count').textContent();await page.locator('#filter-query').fill('zz-no-records-zz');await page.waitForTimeout(200);if(!await page.locator('#transaction-results').getByText('Nenhum lançamento por aqui').isVisible())throw Error('Search failed');await page.locator('#filter-query').fill('');await page.waitForTimeout(200);await page.locator('[data-action="new-transaction"]').first().click();await page.locator('#field-description').fill('Teste de formulário não salvo');await page.locator('[data-transaction-type="income"]').click();if(await page.locator('#field-description').inputValue()!=='Teste de formulário não salvo')throw Error('Form lost input on type change');page.once('dialog',dialog=>dialog.accept());await page.locator('#close-dialog').click();
await page.setViewportSize({width:390,height:844});await page.locator('.nav-link[href="#overview"]').first().click();await page.screenshot({path:path.join(__dirname,'../.local-tools/screenshots/overview-mobile.png'),fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile horizontal overflow');await page.locator('#more-nav').click();await page.locator('a[href="#dna"]').first().click();await page.screenshot({path:path.join(__dirname,'../.local-tools/screenshots/dna-mobile.png'),fullPage:true});
await page.locator('#logout').evaluate(el=>el.click());await page.locator('#auth').waitFor({state:'visible'});if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({passed:views.length+6,transactions:countText,desktop:'1440x1080',mobile:'390x844',consoleErrors:errors.length,writeRequests:0}));}
finally{await browser.close();}})().catch(e=>{console.error('Browser check failed:',e.message);process.exitCode=1;});
