const {execFile}=require('node:child_process'),{promisify}=require('node:util'),fs=require('node:fs'),path=require('node:path');const exec=promisify(execFile);
const adb='C:/Users/User/AppData/Local/Android/Sdk/platform-tools/adb.exe',serial='emulator-5580';const email=process.env.CONTROLEGASTOS_LOGIN_EMAIL,password=process.env.CONTROLEGASTOS_LOGIN_PASSWORD;delete process.env.CONTROLEGASTOS_LOGIN_EMAIL;delete process.env.CONTROLEGASTOS_LOGIN_PASSWORD;
const run=async args=>(await exec(adb,['-s',serial,...args],{windowsHide:true,maxBuffer:5e6})).stdout;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function nodes(){await run(['shell','uiautomator','dump','/sdcard/em-casa-ui.xml']);const xml=await run(['shell','cat','/sdcard/em-casa-ui.xml']);return [...xml.matchAll(/<node\s+([^>]+)>?/g)].map(m=>Object.fromEntries([...m[1].matchAll(/([\w-]+)="([^"]*)"/g)].map(x=>[x[1],x[2]])));}
async function tap(pattern){const list=await nodes();const n=list.find(n=>pattern.test(n['content-desc']||'')&&n.clickable==='true')||list.find(n=>pattern.test(n.text||''));if(!n)throw Error('Control not found: '+pattern.source);const b=n.bounds.match(/\d+/g).map(Number);await run(['shell','input','tap',String(Math.round((b[0]+b[2])/2)),String(Math.round((b[1]+b[3])/2))]);await pause(400);}
async function assertText(pattern){if(!(await nodes()).some(n=>pattern.test(n.text||'')||pattern.test(n['content-desc']||'')))throw Error('Screen not found: '+pattern.source);}
async function screenshot(name){const{stdout}=await exec(adb,['-s',serial,'exec-out','screencap','-p'],{windowsHide:true,encoding:'buffer',maxBuffer:10e6});fs.writeFileSync(path.join(__dirname,'../.local-tools/screenshots',name+'.png'),stdout);}
(async()=>{await run(['shell','am','start','-n','com.awfinance.app/.MainActivity']);await pause(1500);if((await nodes()).some(n=>n['content-desc']==='E-mail')){if(!/^[\w@.+-]+$/.test(email)||!/^[\w.@+-]+$/.test(password))throw Error('Unsupported input characters');await tap(/^E-mail$/);await run(['shell','input','text',email]);await run(['shell','input','keyevent','4']);await tap(/^Senha$/);await run(['shell','input','text',password]);await run(['shell','input','keyevent','4']);await tap(/^Entrar$/);await pause(4000);}await assertText(/Seu mês, com clareza/);await screenshot('android-overview');await tap(/^Lançamentos/);await assertText(/Seu histórico|SEU HISTÓRICO/);await tap(/^Novo lançamento$/);await assertText(/^Valor \(R\$\)$/);await tap(/^Fechar formulário$/);await tap(/^Cartões/);await assertText(/Cartões e faturas/);await tap(/^Relatórios/);await assertText(/Entenda seus gastos/);await tap(/^DNA dos gastos$/);await assertText(/Custo médio mensal/);await screenshot('android-dna');await tap(/^Mais/);await assertText(/Sua organização/);await tap(/^Contas e saldos/);await tap(/^Nova conta|^＋ Nova conta/);await assertText(/Saldo inicial/);await tap(/^Fechar formulário$/);await run(['shell','am','force-stop','com.awfinance.app']);await run(['shell','am','start','-n','com.awfinance.app/.MainActivity']);await pause(2500);await assertText(/Seu mês, com clareza/);await tap(/^Mais/);await run(['shell','input','swipe','520','1820','520','550','400']);await pause(400);await tap(/^Sair neste aparelho$/);await tap(/^Sair$/i);await assertText(/^em casa\.$/);console.log(JSON.stringify({passed:['native login','overview','transactions','transaction modal','cards','reports and DNA','accounts form','session survives restart','local logout'],financialWrites:0}));})().catch(e=>{console.error('Android check failed:',e.message);process.exitCode=1;});
